- name: Deploy to Server
  uses: appleboy/ssh-action@v0.1.6
  with:
    host: ${{ secrets.HOST }}
    username: ec2-user
    key: ${{ secrets.EC2_KEY }}
    script: |
      cd /var/www/docker-node-app

      git pull origin main

      docker stop myapp || true
      docker rm myapp || true

      docker build -t my-node-app .
      docker run -d -p 3000:3000 --name myapp my-node-app

      sudo systemctl restart nginx