name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/docker-node-app

            git pull origin main

            docker stop myapp || true
            docker rm myapp || true

            docker build -t my-node-app .
            docker run -d -p 3000:3000 --name myapp my-node-app

            sudo systemctl restart nginx